#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	clamav
	exim_mailqueue
	exim_mailstats
	redis_replication_status
"

# rblcheck.sh version
RBLCHECK_VERSION=1.3
RBLCHECK_URL="https://raw.githubusercontent.com/drscream/rblcheck.sh/v${RBLCHECK_VERSION}/rblcheck.sh"

# Exit if any commands fail
set -o errexit

echo "* Create clamav logging directory"
mkdir -p /var/log/clamav
chown clamav:clamav /var/log/clamav

echo "* Create ssl folder"
mkdir -p /opt/local/etc/exim/ssl

echo "* Copy mailer.conf to /etc/ because of exim usage"
cp /opt/local/share/examples/exim/mailer.conf /etc/

echo "* Create folders for redis api-repl"
mkdir -p /var/db/redis/{api-repl,rspamd}
chown -R redis:redis /var/db/redis

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Download rblcheck.sh"
( cd /opt/core/bin && curl -O ${RBLCHECK_URL} && chmod 755 rblcheck.sh )

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
