#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	clamav
	exim_mailqueue
	exim_mailstats
	spamassassin
	redis_replication_status
"

# Exit if any commands fail
set -o errexit

echo "* Create ssl folder"
mkdir -p /opt/local/etc/exim/ssl

echo "* Copy mailer.conf to /etc/ because of exim usage"
cp /opt/local/share/examples/exim/mailer.conf /etc/

echo "* Install rblwatch script"
pip install rblwatch

echo "* Fix rspamd PID directory to /var/run"
gsed -i 's:$RUNDIR:/var/run:g' /opt/local/etc/rspamd/rspamd.conf

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
