#!/bin/bash

# prefix for spipe pipes for scanner
SPREF='scan-'

# FMRI for spiped
SFMRI='svc:/pkgsrc/spiped'

SCANFMRI="${SFMRI}:${SPREF}*"
STARTPORT=42000

# Exims scanner config
EXIMSC='/opt/local/etc/exim/configure.scanner'

# read scan hosts from mdata
SCANHOST="$(mdata-get scan_host 2>/dev/null)"

## remove all scan spipes
for SCANPIPE in $(/usr/bin/svcs -H -o FMRI $SCANFMRI 2>/dev/null)
do
  if [ -n "$SCANPIPE" ]
  then
    /usr/sbin/svcadm disable $SCANPIPE
    /usr/sbin/svccfg delete -f $SCANPIPE
  fi
done

## Scan Hosts in mdata?
if [ -z "$SCANHOST" ]
then 
  ## No
  ## create exim config for local scanner
  rm $EXIMSC 1>/dev/null 2>&1
  ln -s "${EXIMSC}.local" $EXIMSC 1>/dev/null 2>&1
  ## start local scanner
  /usr/sbin/svcadm enable svc:/pkgsrc/clamav:clamd
  /usr/sbin/svcadm enable svc:/network/spamd:default
else 
  ## Yes
  CLAMEXIM=''
  SPAMEXIM=''
  for SPHOST in ${SCANHOST}
  do
    # predefined destination pworts - defined by core.io-scan zone
    # 53310 for clamav, 51133 for spamassassin
    for SPPORT in 53310 51133
    do
      ## Port in use?
      while (/usr/bin/netstat -a -n -f inet -f inet6 | grep -q ".$STARTPORT ")
      do
        let STARTPORT=STARTPORT+1
      done
      ## create spipe smf with $STARTPORT
      /opt/core/bin/spiped-configure-smf ${SPREF}${STARTPORT} encrypt [127.0.0.1]:${STARTPORT} ${SPHOST}:${SPPORT} $(mdata-get scan_key)
      ## save it to create exim config later
      case $SPPORT in
      53310)
        # clamav
        CLAMEXIM="${CLAMEXIM}127.0.0.1 $STARTPORT : "
        ;;
      51133)
        # spamassassin
        SPAMEXIM="${SPAMEXIM}127.0.0.1 $STARTPORT : "
        ;;
      esac
      let STARTPORT=STARTPORT+1
    done
  done

  ## create exim config to use remote/spipe scanner
  rm $EXIMSC 1>/dev/null 2>&1
  echo "# Generated by mdata 20-scan-spiped script" >$EXIMSC
  echo "av_scanner = clamd:${CLAMEXIM}" >>$EXIMSC
  echo "spamd_address = ${SPAMEXIM}" >>$EXIMSC

  ## stop local scanner
  /usr/sbin/svcadm disable svc:/pkgsrc/clamav:clamd
  /usr/sbin/svcadm disable svc:/network/spamd:default
fi


