#!/bin/bash

# prefix for spipe pipes for scanner
SPREF='scan-'

# FMRI for spiped
SFMRI='svc:/pkgsrc/spiped'

SCANFMRI="${SFMRI}${SPREF}*"
STARTPORT=42000

# Exims scanner config
EXIMSC='/local/etc/exim/configure.scanner'

# read scan hosts from mdata
SCANHOST=$(mdata-get scan-host)

## remove all scan spipes
for SCANPIPE in $(/usr/bin/svcs -H -o FMRI $SCANFMRI)
do
  /usr/sbin/svcadm disable $SCANPIPE
  /usr/sbin/svccfg delete -f $SCANPIPE
done

## Scan Hosts in mdata?
if [ -z "$SCANHOST" ]
then 
  ## No
  ## create exim config for local scanner
  ln -s "${EXIMSC}.local" $EXIMSC
  ## start local scanner
  /usr/sbin/svcadm enable svc:/pkgsrc/clamav:clamd
  /usr/sbin/svcadm enable svc:/network/spamd:default
else 
  ## Yes
  EXIMLIST=''
  for SPHOST in ${SCANHOST}
  do
    ## Port in use?
    while (/usr/bin/netstat -a -n -f inet -f inet6 | grep -q ".$STARTPORT ")
    do
      let STARTPORT=STARTPORT+1
    done
    ## create spipe smf with $STARTPORT
    /opt/core/bin/spiped-configure-smf $PREF-$STARTPORT encrypt [127.0.0.1]:$STARTPORT $SPHOST $(mdata-get scan-key)
    ## save it to create exim config later
    EXIMLIST="${EXIMLIST}127.0.0.1 $STARTPORT : "
  done

  ## create exim config to use remote/spipe scanner
  echo "# Generated by mdata 20-scan-spiped script" >$EXIMSC
  echo "av_scanner = clamd:${EXIMLIST}" >>$EXIMSC
  echo "spamd_address = ${EXIMLIST}" >>$EXIMSC

  ## stop local scanner
  /usr/sbin/svcadm disable svc:/pkgsrc/clamav:clamd
  /usr/sbin/svcadm disable svc:/network/spamd:default
fi


